spring.application.name=Gruppe-3-nskesky-Fullstack
spring.datasource.username=root
#Skriv jeres eget password
spring.datasource.password=522589
spring.datasource.url=jdbc:mysql://localhost:3306/cloudwishproject
